'use client';

import { useState } from 'react';

/* ── Data-driven interaction renderer ──
   Renders structured interaction data generated by the pipeline.
   5 types: compare, trace/step-through, simulate, classify, rebuild.
   No per-course custom code — pure data → UI mapping.
*/

interface InteractionData {
  type: string;
  title: string;
  description: string;
  insight: string;
  [key: string]: unknown;
}

interface InteractionRendererProps {
  data: InteractionData;
}

/* ── Compare ── */

function CompareRenderer({ data }: { data: InteractionData }) {
  const items = (data.items || []) as Array<{ id: string; label: string; detail: string; pros?: string[]; cons?: string[] }>;
  const dimensions = (data.dimensions || []) as Array<{ name: string; description: string }>;
  const [selected, setSelected] = useState<string | null>(null);

  return (
    <div>
      <p className="text-sm text-[color:var(--color-muted)] mb-4">{data.description}</p>
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
        {items.map((item) => (
          <button
            key={item.id}
            onClick={() => setSelected(selected === item.id ? null : item.id)}
            className={`rounded-lg border p-4 text-left transition ${
              selected === item.id
                ? 'border-[color:var(--color-accent)] bg-blue-50/50 dark:bg-blue-500/10'
                : 'border-[color:var(--color-border)] hover:border-[color:var(--color-accent)]'
            }`}
          >
            <div className="text-sm font-semibold text-[color:var(--color-text)]">{item.label}</div>
            <p className="mt-1 text-xs text-[color:var(--color-muted)] leading-relaxed">{item.detail}</p>
            {selected === item.id && (
              <div className="mt-3 space-y-2">
                {item.pros && item.pros.length > 0 && (
                  <div>{item.pros.map((p, i) => <span key={i} className="mr-1.5 inline-block rounded bg-emerald-100 px-1.5 py-0.5 text-[10px] text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300">+ {p}</span>)}</div>
                )}
                {item.cons && item.cons.length > 0 && (
                  <div>{item.cons.map((c, i) => <span key={i} className="mr-1.5 inline-block rounded bg-red-100 px-1.5 py-0.5 text-[10px] text-red-700 dark:bg-red-500/15 dark:text-red-300">- {c}</span>)}</div>
                )}
              </div>
            )}
          </button>
        ))}
      </div>
      {dimensions.length > 0 && (
        <div className="mt-4 space-y-2">
          <div className="text-xs font-medium text-[color:var(--color-muted)]">比较维度</div>
          {dimensions.map((d, i) => (
            <div key={i} className="text-xs text-[color:var(--color-text)]"><span className="font-medium">{d.name}：</span>{d.description}</div>
          ))}
        </div>
      )}
    </div>
  );
}

/* ── Trace / Step-through ── */

function TraceRenderer({ data }: { data: InteractionData }) {
  const steps = (data.steps || []) as Array<{ id: string; label: string; detail: string; state: string; highlight: string }>;
  const [current, setCurrent] = useState(0);
  const step = steps[current];

  if (!step) return null;

  return (
    <div>
      <p className="text-sm text-[color:var(--color-muted)] mb-4">{data.description}</p>
      {/* Progress */}
      <div className="mb-4 flex gap-1">
        {steps.map((_, i) => (
          <button
            key={i}
            onClick={() => setCurrent(i)}
            className={`h-1.5 flex-1 rounded-full transition ${i <= current ? 'bg-[color:var(--color-accent)]' : 'bg-[color:var(--color-border)]'}`}
          />
        ))}
      </div>
      {/* Current step */}
      <div className="rounded-lg border border-[color:var(--color-border)] p-4">
        <div className="flex items-center gap-2 mb-2">
          <span className="flex h-6 w-6 items-center justify-center rounded-full bg-[color:var(--color-accent)] text-[10px] font-bold text-white">{current + 1}</span>
          <span className="text-sm font-semibold text-[color:var(--color-text)]">{step.label}</span>
        </div>
        <p className="text-sm text-[color:var(--color-text)] leading-relaxed">{step.detail}</p>
        {step.state && (
          <div className="mt-3 rounded-lg bg-zinc-100 px-3 py-2">
            <pre className="text-xs text-zinc-800 whitespace-pre-wrap font-mono">{step.state}</pre>
          </div>
        )}
        {step.highlight && (
          <div className="mt-2 text-xs font-medium text-[color:var(--color-accent)]">{step.highlight}</div>
        )}
      </div>
      {/* Navigation */}
      <div className="mt-3 flex justify-between">
        <button
          onClick={() => setCurrent(Math.max(0, current - 1))}
          disabled={current === 0}
          className="rounded px-3 py-1.5 text-xs font-medium text-[color:var(--color-muted)] transition hover:text-[color:var(--color-text)] disabled:opacity-30"
        >
          上一步
        </button>
        <span className="text-xs text-[color:var(--color-muted)] self-center">{current + 1} / {steps.length}</span>
        <button
          onClick={() => setCurrent(Math.min(steps.length - 1, current + 1))}
          disabled={current === steps.length - 1}
          className="rounded px-3 py-1.5 text-xs font-medium text-[color:var(--color-accent)] transition hover:opacity-80 disabled:opacity-30"
        >
          下一步
        </button>
      </div>
    </div>
  );
}

/* ── Simulate / Parameter-play ── */

function SimulateRenderer({ data }: { data: InteractionData }) {
  const parameters = (data.parameters || []) as Array<{ id: string; label: string; min: number; max: number; default: number; step: number; unit?: string }>;
  const presets = (data.presets || []) as Array<{ label: string; values: Record<string, number>; note: string }>;
  const computeDesc = (data.computeDescription || '') as string;

  const [values, setValues] = useState<Record<string, number>>(() => {
    const init: Record<string, number> = {};
    for (const p of parameters) init[p.id] = p.default;
    return init;
  });

  const setValue = (id: string, v: number) => setValues((prev) => ({ ...prev, [id]: v }));
  const applyPreset = (preset: { values: Record<string, number> }) => setValues({ ...values, ...preset.values });

  return (
    <div>
      <p className="text-sm text-[color:var(--color-muted)] mb-4">{data.description}</p>
      <div className="space-y-4">
        {parameters.map((p) => (
          <div key={p.id}>
            <div className="flex items-center justify-between mb-1">
              <label className="text-xs font-medium text-[color:var(--color-text)]">{p.label}</label>
              <span className="text-xs font-mono font-semibold text-[color:var(--color-accent)]">
                {values[p.id]}{p.unit ? ` ${p.unit}` : ''}
              </span>
            </div>
            <input
              type="range"
              min={p.min}
              max={p.max}
              step={p.step}
              value={values[p.id]}
              onChange={(e) => setValue(p.id, parseFloat(e.target.value))}
              className="w-full accent-blue-500"
            />
          </div>
        ))}
      </div>
      {presets.length > 0 && (
        <div className="mt-3 flex flex-wrap gap-2">
          {presets.map((preset, i) => (
            <button
              key={i}
              onClick={() => applyPreset(preset)}
              className="rounded-full border border-[color:var(--color-border)] px-2.5 py-1 text-[10px] text-[color:var(--color-muted)] transition hover:border-[color:var(--color-accent)] hover:text-[color:var(--color-accent)]"
              title={preset.note}
            >
              {preset.label}
            </button>
          ))}
        </div>
      )}
      {computeDesc && (
        <div className="mt-4 rounded-lg bg-zinc-100 px-3 py-2">
          <p className="text-xs text-zinc-800 leading-relaxed">{computeDesc}</p>
        </div>
      )}
    </div>
  );
}

/* ── Classify ── */

function ClassifyRenderer({ data }: { data: InteractionData }) {
  const categories = (data.categories || []) as Array<{ id: string; label: string; description: string }>;
  const items = (data.items || []) as Array<{ id: string; content: string; correctCategory: string; explanation: string }>;
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [showResults, setShowResults] = useState(false);

  const handleSelect = (itemId: string, catId: string) => {
    if (showResults) return;
    setAnswers((prev) => ({ ...prev, [itemId]: catId }));
  };

  const allAnswered = items.length > 0 && Object.keys(answers).length === items.length;
  const score = items.filter((item) => answers[item.id] === item.correctCategory).length;

  return (
    <div>
      <p className="text-sm text-[color:var(--color-muted)] mb-4">{data.description}</p>
      {/* Category legend */}
      <div className="mb-4 flex flex-wrap gap-2">
        {categories.map((cat) => (
          <div key={cat.id} className="rounded-full border border-[color:var(--color-border)] px-2.5 py-1 text-[10px] text-[color:var(--color-text)]" title={cat.description}>
            {cat.label}
          </div>
        ))}
      </div>
      {/* Items */}
      <div className="space-y-3">
        {items.map((item) => (
          <div key={item.id} className="rounded-lg border border-[color:var(--color-border)] p-3">
            <p className="text-sm text-[color:var(--color-text)] mb-2">{item.content}</p>
            <div className="flex flex-wrap gap-1.5">
              {categories.map((cat) => {
                const isSelected = answers[item.id] === cat.id;
                const isCorrect = showResults && cat.id === item.correctCategory;
                const isWrong = showResults && isSelected && cat.id !== item.correctCategory;
                return (
                  <button
                    key={cat.id}
                    onClick={() => handleSelect(item.id, cat.id)}
                    className={`rounded-full border px-2 py-0.5 text-[10px] font-medium transition ${
                      isCorrect ? 'border-emerald-400 bg-emerald-50 text-emerald-700 dark:bg-emerald-500/15 dark:text-emerald-300'
                      : isWrong ? 'border-red-400 bg-red-50 text-red-700 dark:bg-red-500/15 dark:text-red-300'
                      : isSelected ? 'border-[color:var(--color-accent)] bg-blue-50 text-blue-700 dark:bg-blue-500/10 dark:text-blue-300'
                      : 'border-[color:var(--color-border)] text-[color:var(--color-muted)] hover:border-[color:var(--color-accent)]'
                    }`}
                  >
                    {cat.label}
                  </button>
                );
              })}
            </div>
            {showResults && (
              <p className="mt-2 text-[10px] text-[color:var(--color-muted)]">{item.explanation}</p>
            )}
          </div>
        ))}
      </div>
      {allAnswered && !showResults && (
        <button
          onClick={() => setShowResults(true)}
          className="mt-4 w-full rounded-lg bg-[color:var(--color-accent)] py-2 text-xs font-medium text-white transition hover:opacity-90"
        >
          检查答案
        </button>
      )}
      {showResults && (
        <div className="mt-3 text-center text-sm font-medium text-[color:var(--color-text)]">
          {score}/{items.length} 正确
        </div>
      )}
    </div>
  );
}

/* ── Rebuild (ordering exercise) ── */

function RebuildRenderer({ data }: { data: InteractionData }) {
  const pieces = (data.pieces || []) as Array<{ id: string; label: string; correctPosition: number }>;
  const targetStructure = (data.targetStructure || '') as string;
  const [order, setOrder] = useState<string[]>(() => {
    // Shuffle pieces
    const ids = pieces.map((p) => p.id);
    for (let i = ids.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [ids[i], ids[j]] = [ids[j], ids[i]];
    }
    return ids;
  });
  const [checked, setChecked] = useState(false);

  const moveUp = (idx: number) => {
    if (idx === 0 || checked) return;
    const next = [...order];
    [next[idx], next[idx - 1]] = [next[idx - 1], next[idx]];
    setOrder(next);
  };

  const isCorrect = (pieceId: string, position: number) => {
    const piece = pieces.find((p) => p.id === pieceId);
    return piece ? piece.correctPosition === position + 1 : false;
  };

  const allCorrect = order.every((id, i) => isCorrect(id, i));

  return (
    <div>
      <p className="text-sm text-[color:var(--color-muted)] mb-2">{data.description}</p>
      {targetStructure && (
        <p className="text-xs text-[color:var(--color-muted)] mb-4 italic">{targetStructure}</p>
      )}
      <div className="space-y-1.5">
        {order.map((id, idx) => {
          const piece = pieces.find((p) => p.id === id);
          if (!piece) return null;
          const correct = checked && isCorrect(id, idx);
          const wrong = checked && !isCorrect(id, idx);
          return (
            <button
              key={id}
              onClick={() => moveUp(idx)}
              className={`flex w-full items-center gap-2 rounded-lg border p-2.5 text-left text-sm transition ${
                correct ? 'border-emerald-400 bg-emerald-50/50 dark:bg-emerald-500/10'
                : wrong ? 'border-red-400 bg-red-50/50 dark:bg-red-500/10'
                : 'border-[color:var(--color-border)] hover:border-[color:var(--color-accent)]'
              }`}
            >
              <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded text-[10px] font-bold text-[color:var(--color-muted)] bg-[color:var(--color-bg)]">
                {idx + 1}
              </span>
              <span className="text-[color:var(--color-text)]">{piece.label}</span>
            </button>
          );
        })}
      </div>
      <div className="mt-3 flex gap-2">
        {!checked && (
          <button
            onClick={() => setChecked(true)}
            className="flex-1 rounded-lg bg-[color:var(--color-accent)] py-2 text-xs font-medium text-white transition hover:opacity-90"
          >
            检查顺序
          </button>
        )}
        {checked && !allCorrect && (
          <button
            onClick={() => setChecked(false)}
            className="flex-1 rounded-lg border border-[color:var(--color-border)] py-2 text-xs font-medium text-[color:var(--color-text)] transition hover:bg-zinc-100"
          >
            继续调整
          </button>
        )}
        {checked && allCorrect && (
          <div className="flex-1 text-center text-sm font-medium text-emerald-600 dark:text-emerald-400 py-2">
            顺序正确!
          </div>
        )}
      </div>
    </div>
  );
}

/* ── Main renderer ── */

const RENDERERS: Record<string, React.ComponentType<{ data: InteractionData }>> = {
  compare: CompareRenderer,
  trace: TraceRenderer,
  'step-through': TraceRenderer,
  simulate: SimulateRenderer,
  'parameter-play': SimulateRenderer,
  classify: ClassifyRenderer,
  rebuild: RebuildRenderer,
  retrieve: ClassifyRenderer,
};

export default function InteractionRenderer({ data }: InteractionRendererProps) {
  const Renderer = RENDERERS[data.type];
  if (!Renderer) return null;

  return (
    <div className="my-10 rounded-xl border border-[color:var(--color-border)] bg-[color:var(--color-panel)] overflow-hidden">
      <div className="border-b border-[color:var(--color-border)] px-5 py-4">
        <h3 className="text-sm font-semibold text-[color:var(--color-text)]">{data.title}</h3>
      </div>
      <div className="px-5 py-5">
        <Renderer data={data} />
      </div>
      {data.insight && (
        <div className="border-t border-[color:var(--color-border)] px-5 py-3 bg-blue-50/50 dark:bg-blue-500/5">
          <p className="text-xs text-blue-700 dark:text-blue-300">
            <span className="font-semibold">关键认知：</span>{data.insight}
          </p>
        </div>
      )}
    </div>
  );
}
